<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Wed May 30 2018 12:10:07 GMT+0000 (UTC)). */
return array(
	'i18n-react' => '0.6.4',
	'immer' => '1.2.1',
	'mobx' => '4.2.0',
	'mobx-state-tree' => '2.0.4',
	'react' => '16.3.2',
	'react-aiot' => '1.2.8',
	'react-dom' => '16.3.2',
	'sortablejs' => '1.7.0'
);
